
# Simple workflow for deploying static content to GitHub Pages
name: Deploy to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v4

      - name: 设置 GitHub Pages 配置
        uses: actions/configure-pages@v5

      - name: 将整个仓库作为工件上传
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
